print("What is your name?")
name = input()
print("Hello,", name)
print("what is your favarite food")
food=input()
print("so how old are you",(name))
age=int(input())
print(age)
birth_date=2025-age
print("I think your birth is at",(birth_date))
